# Generated by Django 5.2.1 on 2025-06-09 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
                'unique_together': {('user', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bank', models.CharField(max_length=100)),
                ('no_rekening', models.CharField(blank=True, max_length=50, null=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekening', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rekening',
                'unique_together': {('user', 'nama_bank', 'no_rekening')},
            },
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=255)),
                ('jumlah_tagihan', models.DecimalField(decimal_places=2, help_text='Jumlah Tagihan', max_digits=12)),
                ('hari_jatuh_tempo', models.PositiveIntegerField(help_text='Tanggal jatuh tempo setiap bulan (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('aktif', models.BooleanField(default=True, help_text='Nonaktifkan jika tidak lagi menjadi tagihan wajib')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaksi.kategori')),
                ('rekening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan', to='transaksi.rekening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tagihan',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=255)),
                ('jumlah', models.DecimalField(decimal_places=2, help_text='Jumlah transaksi dalam Rupiah', max_digits=12)),
                ('jenis', models.CharField(choices=[('IN', 'Pemasukan'), ('OUT', 'Pengeluaran')], max_length=3)),
                ('tanggal', models.DateField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaksi.kategori')),
                ('rekening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='transaksi.rekening')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.CreateModel(
            name='StatusTagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tahun', models.PositiveIntegerField()),
                ('status_lunas', models.BooleanField(default=False)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_tagihan', to='transaksi.tagihan')),
                ('transaksi_pembayaran', models.OneToOneField(blank=True, help_text='Transaksi yang digunakan untuk melunasi tagihan ini', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaksi.transaksi')),
            ],
            options={
                'verbose_name_plural': 'Status Pembayaran Wajib',
                'unique_together': {('tagihan', 'bulan', 'tahun')},
            },
        ),
    ]
