# Generated by Django 5.2.1 on 2025-06-08 05:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
                'unique_together': {('user', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=255)),
                ('jumlah', models.DecimalField(decimal_places=2, help_text='Jumlah transaksi dalam Rupiah', max_digits=12)),
                ('jenis', models.CharField(choices=[('IN', 'Pemasukan'), ('OUT', 'Pengeluaran')], max_length=3)),
                ('tanggal', models.DateField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaksi.kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
            },
        ),
        migrations.CreateModel(
            name='TransaksiWajib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=255)),
                ('jumlah_estimasi', models.DecimalField(decimal_places=2, help_text='Estimasi jumlah pengeluaran', max_digits=12)),
                ('hari_jatuh_tempo', models.PositiveIntegerField(help_text='Tanggal jatuh tempo setiap bulan (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('aktif', models.BooleanField(default=True, help_text='Nonaktifkan jika tidak lagi menjadi transaksi wajib')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaksi.kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_wajib', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaksi Wajib',
            },
        ),
        migrations.CreateModel(
            name='StatusPembayaranWajib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tahun', models.PositiveIntegerField()),
                ('status_lunas', models.BooleanField(default=False)),
                ('transaksi_pembayaran', models.OneToOneField(blank=True, help_text='Transaksi yang digunakan untuk melunasi tagihan ini', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaksi.transaksi')),
                ('transaksi_wajib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_pembayaran', to='transaksi.transaksiwajib')),
            ],
            options={
                'verbose_name_plural': 'Status Pembayaran Wajib',
                'unique_together': {('transaksi_wajib', 'bulan', 'tahun')},
            },
        ),
    ]
